# Generated by Django 4.2.1 on 2023-11-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(),
        ),
    ]
