# Generated by Django 4.2.1 on 2023-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0004_messagetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetest',
            name='supabaseID',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
