# Generated by Django 4.2.1 on 2024-01-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0005_messagetest_supabaseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
