# Generated by Django 4.2.1 on 2023-09-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_user_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('ENHANCED', 'Enhanced'), ('ULTIMATE', 'Ultimate'), ('ADMIN', 'Admin')], default='FREE'),
        ),
    ]
