# Generated by Django 4.2.1 on 2023-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_alter_user_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripeCustomerID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
