# Generated by Django 4.2.1 on 2023-12-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_user_stripecustomerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabaseID',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
